import mongoose from 'mongoose';

const interviewSessionSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    analysis: { type: mongoose.Schema.Types.ObjectId, ref: 'JobAnalysis', required: true },
    job: {
      title: String,
      company: String,
      location: String,
      url: String
    },
    status: {
      type: String,
      enum: ['in_progress', 'complete', 'abandoned'],
      default: 'in_progress',
      index: true
    },
    // Full conversation: [{ question, answer, evaluation }]
    history: { type: mongoose.Schema.Types.Mixed, default: [] },
    questionCount: { type: Number, default: 0 },
    maxQuestions: { type: Number, default: 8 },
    // Detailed report card generated by the LangGraph flow when complete
    report: { type: mongoose.Schema.Types.Mixed, default: null },
    completedAt: Date
  },
  { timestamps: true }
);

interviewSessionSchema.index({ user: 1, createdAt: -1 });

export default mongoose.model('InterviewSession', interviewSessionSchema);