import { jsPDF } from 'jspdf';

const COLORS = {
  primary: [99, 102, 241],   // indigo-500
  dark: [15, 23, 42],        // slate-900
  text: [148, 163, 184],     // slate-400
  white: [255, 255, 255],
  heading: [224, 231, 255],  // indigo-100
  emerald: [52, 211, 153],
  red: [248, 113, 113],
  amber: [251, 191, 36],
};

function addPageHeader(doc, title, subtitle, pageWidth) {
  // Dark header bar
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, pageWidth, 32, 'F');

  // Indigo accent line
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 32, pageWidth, 2, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.heading);
  doc.text(title, 14, 18);

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.text);
    doc.text(subtitle, 14, 27);
  }
}

function addFooter(doc, pageWidth, pageHeight, pageNum, totalPages) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, pageHeight - 12, pageWidth, 12, 'F');
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.text);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Job Hunt Assistant', 14, pageHeight - 4);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 14, pageHeight - 4, { align: 'right' });
}

function wrapText(doc, text, x, y, maxWidth, lineHeight) {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function chunkArray(arr, size) {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) chunks.push(arr.slice(i, i + size));
  return chunks;
}

// ─── RESUME PARSING (plain text → structured sections) ─────────────────────
// The AI backend returns the tailored resume as a plain text blob, so we
// infer structure heuristically, tuned to match the classic "Jake's Resume"
// LaTeX layout: NAME / tagline / contact line, then ALL-CAPS section
// headings, each containing either:
//   - a title/institution line immediately followed by a "Degree ... Dates"
//     or "Role ... Dates" line (dates right-aligned), as in EDUCATION
//   - a "Project Title ... Date range" line on its own (PROJECTS)
//   - "Label: comma, separated, list" lines (TECHNICAL SKILLS)
//   - bullet lines for accomplishments

const BULLET_RE = /^[-*•‣→●◦]\s+/;
const MONTHS = 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec';
const DATE_TAIL_RE = new RegExp(
  `\\s*((?:${MONTHS})\\.?\\s+\\d{4}\\s*[–—-]\\s*(?:(?:${MONTHS})\\.?\\s+\\d{4}|Present|present|Current|current)|\\d{4}\\s*[–—-]\\s*(?:\\d{4}|Present|present|Current|current))\\s*$`
);
const LABELED_LINE_RE = /^([A-Za-z][A-Za-z /&]{1,40}):\s+(.+)$/;
const CONTACT_HINT_RE = /(@|https?:\/\/|\d{3}.*\d{3}.*\d{3,4})/;

function splitLines(text) {
  return (text || '').replace(/\r\n/g, '\n').split('\n').map((l) => l.trim());
}

function isBullet(line) {
  return BULLET_RE.test(line);
}

function stripBullet(line) {
  return line.replace(BULLET_RE, '');
}

function dateTailSplit(line) {
  const m = line.match(DATE_TAIL_RE);
  if (!m) return null;
  const left = line.slice(0, m.index).trim();
  if (!left) return null;
  return { left, right: m[1].trim() };
}

function isPipeSubheading(line) {
  return line.includes('|') && !isBullet(line) && line.length <= 120;
}

function isHeading(line) {
  if (!line || isBullet(line) || line.includes('|') || dateTailSplit(line) || LABELED_LINE_RE.test(line)) return false;
  const letters = line.replace(/[^A-Za-z]/g, '');
  return letters.length >= 2 && line === line.toUpperCase() && line.length <= 45;
}

function looksLikeContactLine(line) {
  return CONTACT_HINT_RE.test(line);
}

function parseHeaderBlock(lines, startIndex) {
  let i = startIndex;
  const skipBlanks = () => { while (i < lines.length && lines[i] === '') i += 1; };
  // Contact lines legitimately contain '|' separators, so only headings and
  // bullets disqualify a line from being part of the name/tagline/contact
  // block — unlike inside a section body, pipes here don't mean subheading.
  const isPlain = (line) => !isHeading(line) && !isBullet(line);

  skipBlanks();
  let name = '';
  let tagline = '';
  let contact = '';
  if (i < lines.length && isPlain(lines[i])) {
    name = lines[i];
    i += 1;
    skipBlanks();
    if (i < lines.length && isPlain(lines[i])) {
      if (looksLikeContactLine(lines[i])) {
        contact = lines[i];
        i += 1;
      } else {
        tagline = lines[i];
        i += 1;
        skipBlanks();
        if (i < lines.length && isPlain(lines[i]) && looksLikeContactLine(lines[i])) {
          contact = lines[i];
          i += 1;
        }
      }
    }
  }
  return { name, tagline, contact, nextIndex: i };
}

function parseResumeText(text) {
  const lines = splitLines(text);
  const { name, tagline, contact, nextIndex } = parseHeaderBlock(lines, 0);

  const sections = [];
  let current = null;
  for (let i = nextIndex; i < lines.length; i += 1) {
    const line = lines[i];
    if (line === '') continue;

    if (isHeading(line)) {
      current = { heading: line, items: [] };
      sections.push(current);
      continue;
    }
    if (!current) {
      current = { heading: '', items: [] };
      sections.push(current);
    }

    const dateSplit = dateTailSplit(line);
    const labeled = line.match(LABELED_LINE_RE);

    if (isBullet(line)) {
      current.items.push({ type: 'bullet', text: stripBullet(line) });
    } else if (dateSplit) {
      current.items.push({ type: 'subheading', left: dateSplit.left, right: dateSplit.right });
    } else if (isPipeSubheading(line)) {
      const parts = line.split('|').map((p) => p.trim());
      const right = parts.length > 1 ? parts.pop() : '';
      current.items.push({ type: 'subheading', left: parts.join(' | '), right });
    } else if (labeled) {
      current.items.push({ type: 'labeled', label: labeled[1].trim(), rest: labeled[2].trim() });
    } else {
      current.items.push({ type: 'text', text: line });
    }
  }

  // A plain line immediately followed by a dated subheading is an
  // institution/company name (EDUCATION-style two-row entries) — bold it
  // like a mini title rather than rendering it as regular body text.
  for (const section of sections) {
    for (let idx = 0; idx < section.items.length - 1; idx += 1) {
      if (section.items[idx].type === 'text' && section.items[idx + 1].type === 'subheading') {
        section.items[idx] = { type: 'label', text: section.items[idx].text };
      }
    }
  }

  return { name, tagline, contact, sections };
}

// ─── LATEX-STYLE RESUME RENDERING (black on white, serif) ──────────────────

const INK = [17, 17, 17];
const MUTED = [90, 90, 90];
const RULE = [40, 40, 40];

function newPlainPage(doc) {
  doc.addPage();
}

function drawResumeFooters(doc, pageWidth, pageHeight, margin) {
  const totalPages = doc.internal.getNumberOfPages();
  if (totalPages <= 1) return;
  for (let p = 1; p <= totalPages; p += 1) {
    doc.setPage(p);
    doc.setFont('times', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`${p} / ${totalPages}`, pageWidth - margin, pageHeight - 8, { align: 'right' });
  }
}

function ensureRoom(doc, y, needed, pageWidth, pageHeight, margin) {
  if (y + needed <= pageHeight - margin) return y;
  newPlainPage(doc);
  return margin;
}

function drawSectionHeading(doc, heading, x, y, contentWidth) {
  doc.setFont('times', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(...INK);
  doc.text(heading.toUpperCase(), x, y);
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.4);
  doc.line(x, y + 1.4, x + contentWidth, y + 1.4);
  return y + 6.5;
}

function renderResumeBody(doc, resumeText, { margin, pageWidth, pageHeight, contentWidth }) {
  const { name, tagline, contact, sections } = parseResumeText(resumeText);
  let y = margin;

  if (name) {
    doc.setFont('times', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(...INK);
    doc.text(name, pageWidth / 2, y, { align: 'center' });
    y += 7;
  }
  if (tagline) {
    doc.setFont('times', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(...INK);
    doc.text(tagline, pageWidth / 2, y, { align: 'center' });
    y += 5.5;
  }
  if (contact) {
    doc.setFont('times', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text(contact, pageWidth / 2, y, { align: 'center' });
    y += 5;
  }
  if (name || contact) {
    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  }

  for (const section of sections) {
    y = ensureRoom(doc, y, 14, pageWidth, pageHeight, margin);
    if (section.heading) {
      y = drawSectionHeading(doc, section.heading, margin, y, contentWidth);
    }

    for (const item of section.items) {
      if (item.type === 'subheading') {
        y = ensureRoom(doc, y, 6, pageWidth, pageHeight, margin);
        doc.setFont('times', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(...INK);
        doc.text(item.left, margin, y);
        if (item.right) {
          doc.setFont('times', 'italic');
          doc.setFontSize(9.5);
          doc.setTextColor(...MUTED);
          doc.text(item.right, pageWidth - margin, y, { align: 'right' });
        }
        y += 5.2;
      } else if (item.type === 'bullet') {
        doc.setFont('times', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(...INK);
        const lines = doc.splitTextToSize(item.text, contentWidth - 8);
        y = ensureRoom(doc, y, lines.length * 4.6, pageWidth, pageHeight, margin);
        doc.text('•', margin + 1, y);
        doc.text(lines, margin + 5.5, y);
        y += lines.length * 4.6 + 0.8;
      } else if (item.type === 'label') {
        // Institution/company name preceding a dated subheading line.
        doc.setFont('times', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(...INK);
        const lines = doc.splitTextToSize(item.text, contentWidth);
        y = ensureRoom(doc, y, lines.length * 4.8, pageWidth, pageHeight, margin);
        doc.text(lines, margin, y);
        y += lines.length * 4.8 + 0.6;
      } else if (item.type === 'labeled') {
        // "Programming Languages: Python, C++, C" style skills line.
        doc.setFont('times', 'bold');
        doc.setFontSize(9.5);
        const labelText = `${item.label}: `;
        const labelWidth = doc.getTextWidth(labelText);
        doc.setFont('times', 'normal');
        const restLines = doc.splitTextToSize(item.rest, Math.max(contentWidth - labelWidth, 30));
        y = ensureRoom(doc, y, restLines.length * 4.6, pageWidth, pageHeight, margin);
        doc.setFont('times', 'bold');
        doc.setTextColor(...INK);
        doc.text(labelText, margin, y);
        doc.setFont('times', 'normal');
        doc.text(restLines[0] || '', margin + labelWidth, y);
        for (let li = 1; li < restLines.length; li += 1) {
          y += 4.6;
          doc.text(restLines[li], margin, y);
        }
        y += 4.6 + 0.8;
      } else {
        doc.setFont('times', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(...INK);
        const lines = doc.splitTextToSize(item.text, contentWidth);
        y = ensureRoom(doc, y, lines.length * 4.6, pageWidth, pageHeight, margin);
        doc.text(lines, margin, y);
        y += lines.length * 4.6 + 0.8;
      }
    }
    y += 3;
  }

  return y;
}

function renderCoverLetterBody(doc, coverLetterText, { margin, pageWidth, pageHeight, contentWidth }) {
  let y = margin;
  doc.setFont('times', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(...INK);
  doc.text('COVER LETTER', pageWidth / 2, y, { align: 'center' });
  y += 3;
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.4);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  const paragraphs = (coverLetterText || '').replace(/\r\n/g, '\n').split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
  doc.setFont('times', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  for (const para of paragraphs) {
    const lines = doc.splitTextToSize(para, contentWidth);
    y = ensureRoom(doc, y, lines.length * 5, pageWidth, pageHeight, margin);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 4;
  }
}

export function exportResumePDF({ resumeText, coverLetterText, jobTitle, company }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  const geometry = { margin, pageWidth, pageHeight, contentWidth };

  renderResumeBody(doc, resumeText, geometry);

  if (coverLetterText) {
    newPlainPage(doc);
    renderCoverLetterBody(doc, coverLetterText, geometry);
  }

  drawResumeFooters(doc, pageWidth, pageHeight, margin);

  const safeCompany = (company || 'resume').replace(/\s+/g, '_');
  doc.save(`tailored_resume_${safeCompany}.pdf`);
}

// ─── INTERVIEW REPORT EXPORT ─────────────────────────────────────────────────

export function exportInterviewReportPDF({ report, jobTitle, company, history = [] }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  let y = 42;

  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  addPageHeader(doc, 'Interview Report Card', `${jobTitle} at ${company} · ${new Date().toLocaleDateString()}`, pageWidth);

  const score = report.overall_score ?? 0;
  const scoreColor = score >= 70 ? COLORS.emerald : score >= 40 ? COLORS.amber : COLORS.red;

  // Overall score block
  doc.setFillColor(30, 41, 59);
  doc.roundedRect(margin, y, contentWidth, 28, 3, 3, 'F');
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...scoreColor);
  doc.text(`${score}%`, margin + 8, y + 18);
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.text);
  doc.text('Overall Score', margin + 8, y + 24);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.white);
  const summaryLines = doc.splitTextToSize(report.summary || '', contentWidth - 50);
  doc.text(summaryLines, margin + 50, y + 10);
  y += 34;

  const section = (label) => {
    if (y > pageHeight - 30) {
      addFooter(doc, pageWidth, pageHeight, doc.internal.getNumberOfPages(), '…');
      doc.addPage();
      doc.setFillColor(17, 24, 39);
      doc.rect(0, 0, pageWidth, pageHeight, 'F');
      addPageHeader(doc, 'Interview Report (cont.)', '', pageWidth);
      y = 42;
    }
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text(label, margin, y);
    doc.setFillColor(...COLORS.primary);
    doc.rect(margin, y + 1.5, contentWidth, 0.4, 'F');
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.white);
  };

  // Strengths
  section('✓ Strengths');
  for (const s of (report.strengths || [])) {
    y = wrapText(doc, `• ${s}`, margin + 3, y, contentWidth - 3, 5);
    y += 1;
    if (y > pageHeight - 20) { section('Strengths (cont.)'); }
  }
  y += 4;

  // Weaknesses
  section('✗ Areas to Improve');
  for (const w of (report.weaknesses || [])) {
    y = wrapText(doc, `• ${w}`, margin + 3, y, contentWidth - 3, 5);
    y += 1;
    if (y > pageHeight - 20) { section('Areas to Improve (cont.)'); }
  }
  y += 4;

  // Recommendations
  section('💡 Recommendations');
  (report.recommendations || []).forEach((r, i) => {
    y = wrapText(doc, `${i + 1}. ${r}`, margin + 3, y, contentWidth - 3, 5);
    y += 2;
    if (y > pageHeight - 20) { section('Recommendations (cont.)'); }
  });
  y += 4;

  // Per-question breakdown
  if (report.per_question_breakdown?.length) {
    section('📋 Question Breakdown');
    for (const entry of report.per_question_breakdown) {
      if (y > pageHeight - 30) {
        addFooter(doc, pageWidth, pageHeight, doc.internal.getNumberOfPages(), '…');
        doc.addPage();
        doc.setFillColor(17, 24, 39);
        doc.rect(0, 0, pageWidth, pageHeight, 'F');
        addPageHeader(doc, 'Question Breakdown (cont.)', '', pageWidth);
        y = 42;
      }
      const qScore = entry.score ?? 0;
      const qColor = qScore >= 70 ? COLORS.emerald : qScore >= 40 ? COLORS.amber : COLORS.red;
      doc.setFillColor(30, 41, 59);
      const blockH = 18 + (doc.splitTextToSize(entry.feedback || '', contentWidth - 20).length * 4.5);
      doc.roundedRect(margin, y, contentWidth, blockH, 2, 2, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.white);
      doc.text(doc.splitTextToSize(entry.question, contentWidth - 24), margin + 4, y + 7);
      doc.setTextColor(...qColor);
      doc.text(`${qScore}%`, pageWidth - margin - 4, y + 7, { align: 'right' });
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.text);
      doc.text(doc.splitTextToSize(entry.feedback || '', contentWidth - 8), margin + 4, y + 14);
      y += blockH + 4;
    }
  }

  addFooter(doc, pageWidth, pageHeight, doc.internal.getNumberOfPages(), doc.internal.getNumberOfPages());
  doc.save(`interview_report_${company.replace(/\s+/g, '_')}.pdf`);
}

// ─── ATS ANALYSIS EXPORT ─────────────────────────────────────────────────────

export function exportAnalysisPDF({ analysis, jobTitle, company }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  let y = 42;

  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  addPageHeader(doc, 'ATS Analysis Report', `${jobTitle} at ${company} · ${new Date().toLocaleDateString()}`, pageWidth);

  // Score cards row
  const cards = [
    { label: 'ATS Score', value: `${analysis.score ?? 0}%`, color: COLORS.emerald },
    { label: 'Keyword Match', value: `${analysis.keywordMatchScore ?? 0}%`, color: COLORS.primary },
    { label: 'Semantic Score', value: analysis.semanticScore != null ? `${analysis.semanticScore}%` : 'N/A', color: [96, 165, 250] },
    { label: 'Combined', value: analysis.combinedScore != null ? `${analysis.combinedScore}%` : 'N/A', color: COLORS.amber },
  ];
  const cardW = (contentWidth - 9) / 4;
  cards.forEach((card, i) => {
    const cx = margin + i * (cardW + 3);
    doc.setFillColor(30, 41, 59);
    doc.roundedRect(cx, y, cardW, 22, 2, 2, 'F');
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...card.color);
    doc.text(card.value, cx + cardW / 2, y + 12, { align: 'center' });
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.text);
    doc.text(card.label, cx + cardW / 2, y + 19, { align: 'center' });
  });
  y += 30;

  const section = (label) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text(label, margin, y);
    doc.setFillColor(...COLORS.primary);
    doc.rect(margin, y + 1.5, contentWidth, 0.4, 'F');
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.white);
  };

  section('Keywords Found');
  const foundChunks = chunkArray(analysis.found || [], 4);
  for (const row of foundChunks) {
    let rx = margin;
    for (const kw of row) {
      const w = Math.min(doc.getTextWidth(kw) + 6, 50);
      doc.setFillColor(16, 185, 129, 0.15);
      doc.roundedRect(rx, y - 4, w, 7, 1.5, 1.5, 'F');
      doc.setTextColor(...COLORS.emerald);
      doc.setFontSize(8);
      doc.text(kw, rx + 3, y);
      rx += w + 3;
    }
    y += 9;
  }
  y += 4;

  section('Missing Keywords');
  const missingChunks = chunkArray(analysis.missing || [], 4);
  for (const row of missingChunks) {
    let rx = margin;
    for (const kw of row) {
      const w = Math.min(doc.getTextWidth(kw) + 6, 50);
      doc.setFillColor(239, 68, 68, 0.15);
      doc.roundedRect(rx, y - 4, w, 7, 1.5, 1.5, 'F');
      doc.setTextColor(...COLORS.red);
      doc.setFontSize(8);
      doc.text(kw, rx + 3, y);
      rx += w + 3;
    }
    y += 9;
  }
  y += 4;

  if (analysis.smartSuggestions?.length) {
    section('Smart Suggestions');
    doc.setTextColor(...COLORS.white);
    for (const s of analysis.smartSuggestions) {
      if (y > pageHeight - 20) {
        addFooter(doc, pageWidth, pageHeight, 1, 1);
        doc.addPage();
        doc.setFillColor(17, 24, 39);
        doc.rect(0, 0, pageWidth, pageHeight, 'F');
        addPageHeader(doc, 'ATS Analysis (cont.)', '', pageWidth);
        y = 42;
      }
      y = wrapText(doc, `• ${s}`, margin + 3, y, contentWidth - 3, 5);
      y += 3;
    }
  }

  addFooter(doc, pageWidth, pageHeight, 1, 1);
  doc.save(`ats_analysis_${company.replace(/\s+/g, '_')}.pdf`);
}